# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportWidget(object):
    def setupUi(self, ExportWidget):
        ExportWidget.setObjectName("ExportWidget")
        ExportWidget.resize(922, 657)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExportWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ExportWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(ExportWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb_class = QtWidgets.QComboBox(ExportWidget)
        self.cb_class.setObjectName("cb_class")
        self.horizontalLayout.addWidget(self.cb_class)
        self.pb_export = QtWidgets.QPushButton(ExportWidget)
        self.pb_export.setObjectName("pb_export")
        self.horizontalLayout.addWidget(self.pb_export)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(ExportWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(ExportWidget)
        QtCore.QMetaObject.connectSlotsByName(ExportWidget)

    def retranslateUi(self, ExportWidget):
        _translate = QtCore.QCoreApplication.translate
        ExportWidget.setWindowTitle(_translate("ExportWidget", "Form"))
        self.label.setText(_translate("ExportWidget", "导出结果"))
        self.label_2.setText(_translate("ExportWidget", "选择班级："))
        self.pb_export.setText(_translate("ExportWidget", "导出成绩"))
