# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputInfoWidget(object):
    def setupUi(self, InputInfoWidget):
        InputInfoWidget.setObjectName("InputInfoWidget")
        InputInfoWidget.resize(1018, 795)
        self.verticalLayout = QtWidgets.QVBoxLayout(InputInfoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(InputInfoWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_class = QtWidgets.QLineEdit(self.groupBox)
        self.le_class.setObjectName("le_class")
        self.horizontalLayout.addWidget(self.le_class)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.le_filename = QtWidgets.QLineEdit(self.groupBox)
        self.le_filename.setObjectName("le_filename")
        self.horizontalLayout.addWidget(self.le_filename)
        self.pb_choose = QtWidgets.QPushButton(self.groupBox)
        self.pb_choose.setObjectName("pb_choose")
        self.horizontalLayout.addWidget(self.pb_choose)
        self.pb_import_class = QtWidgets.QPushButton(self.groupBox)
        self.pb_import_class.setObjectName("pb_import_class")
        self.horizontalLayout.addWidget(self.pb_import_class)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(InputInfoWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_personnumber = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_personnumber.setObjectName("le_personnumber")
        self.horizontalLayout_2.addWidget(self.le_personnumber)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_personname = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_personname.setObjectName("le_personname")
        self.horizontalLayout_2.addWidget(self.le_personname)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cb_class = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_class.setObjectName("cb_class")
        self.horizontalLayout_2.addWidget(self.cb_class)
        self.pb_import_person = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_import_person.setObjectName("pb_import_person")
        self.horizontalLayout_2.addWidget(self.pb_import_person)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.treeView = QtWidgets.QTreeView(InputInfoWidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)

        self.retranslateUi(InputInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(InputInfoWidget)

    def retranslateUi(self, InputInfoWidget):
        _translate = QtCore.QCoreApplication.translate
        InputInfoWidget.setWindowTitle(_translate("InputInfoWidget", "Form"))
        self.groupBox.setTitle(_translate("InputInfoWidget", "导入班级信息："))
        self.label.setText(_translate("InputInfoWidget", "班级号："))
        self.label_3.setText(_translate("InputInfoWidget", "导入文件："))
        self.pb_choose.setText(_translate("InputInfoWidget", "选择文件"))
        self.pb_import_class.setText(_translate("InputInfoWidget", "开始导入"))
        self.groupBox_2.setTitle(_translate("InputInfoWidget", "导入个人信息："))
        self.label_2.setText(_translate("InputInfoWidget", "考生学号："))
        self.label_4.setText(_translate("InputInfoWidget", "考生姓名："))
        self.label_5.setText(_translate("InputInfoWidget", "考生班级："))
        self.pb_import_person.setText(_translate("InputInfoWidget", "开始导入"))
